return {
  {
    'nvim-telescope/telescope.nvim',
    lazy = true,
    cmd = 'Telescope',
    dependencies = {
      { 'nvim-lua/plenary.nvim', lazy = true },
      { 'ThePrimeagen/harpoon', lazy = true },
    },
    config = function()
      local telescope = require('telescope')
      telescope.load_extension('harpoon')
      telescope.setup({
        pickers = {
          find_files = { theme = 'ivy' },
          git_files = { theme = 'ivy' },
          grep_string = { theme = 'ivy' },
          live_grep = { theme = 'ivy' },
          buffers = { theme = 'ivy' },
          oldfiles = { theme = 'ivy' },
          commands = { theme = 'ivy' },
          tags = { theme = 'ivy' },
          command_history = { theme = 'ivy' },
          search_history = { theme = 'ivy' },
          help_tags = { theme = 'ivy' },
          man_pages = { theme = 'ivy' },
          marks = { theme = 'ivy' },
          colorscheme = { theme = 'ivy' },
          quickfix = { theme = 'ivy' },
          quickfixhistory = { theme = 'ivy' },
          loclist = { theme = 'ivy' },
          jumplist = { theme = 'ivy' },
          vim_options = { theme = 'ivy' },
          registers = { theme = 'ivy' },
          autocommands = { theme = 'ivy' },
          spell_suggest = { theme = 'ivy' },
          keymaps = { theme = 'ivy' },
          filetypes = { theme = 'ivy' },
          highlights = { theme = 'ivy' },
          current_buffer_fuzzy_find = { theme = 'ivy' },
          current_buffer_tags = { theme = 'ivy' },
          resume = { theme = 'ivy' },
          pickers = { theme = 'ivy' },
          lsp_references = { theme = 'ivy' },
          lsp_incoming_calls = { theme = 'ivy' },
          lsp_outgoing_calls = { theme = 'ivy' },
          lsp_document_symbols = { theme = 'ivy' },
          lsp_workspace_symbols = { theme = 'ivy' },
          lsp_dynamic_workspace_symbols = { theme = 'ivy' },
          diagnostics = { theme = 'ivy' },
          lsp_implementations = { theme = 'ivy' },
          lsp_definitions = { theme = 'ivy' },
          lsp_type_definitions = { theme = 'ivy' },
          git_commits = { theme = 'ivy' },
          git_bcommits = { theme = 'ivy' },
          git_branches = { theme = 'ivy' },
          git_status = { theme = 'ivy' },
          git_stash = { theme = 'ivy' },
          treesitter = { theme = 'ivy' },
          planets = { theme = 'ivy' },
          builtin = { theme = 'ivy' },
          reloader = { theme = 'ivy' },
          symbols = { theme = 'ivy' },
        },
      })
    end,
  },
}
